### ISSUE TITLE
dict.h file not found

### ISSUE THREAD

**Issue by Leiyi548** [wasden/cmp-flypy.nvim#2]
本人也是使用小鹤音形的用户（初学者），看到作者的插件，就立马使用，那些 lua.h 都装了，这个dict.h ，不知道是哪里的文件，我也找不到。
![image](https://user-images.githubusercontent.com/76139422/180445057-3f7d3ca3-4133-483c-a9f9-44782e03b85b.png)

**Comment by wasden** [comment]
自动生成在build文件夹下面

**Comment by Leiyi548** [comment]
@wasden  换成archlinux 就没有这个问题了。
