### ISSUE TITLE
请教cmp编写输入法插件的问题

### ISSUE THREAD

**Issue by yaowjit** [wasden/cmp-flypy.nvim#4]
作者您好,我这里不是使用您的插件遇到了问题,而是我现在在尝试直接调用librime来写一个cmp的输入法插件,但是现在遇到了一些问题

我现在设置的pattern和trigger如下
```lua
function source:get_keyword_pattern()
    return [[\l\+]]
end
function source:get_trigger_characters()
    return vim.split("qwertyuiopasdfghjklzxcvbnm", "")
end
```
当光标移动到英文字母之后的时候, 我的插件会自动捕获这个这些英文,然后自动触发,像下面这样
![Peek 2023-02-12 21-37](https://user-images.githubusercontent.com/36393630/218315928-baad9299-cb52-4f25-a181-8550d82bc9fc.gif)

我看您的插件好像没有这样的问题,请问您是怎么处理的,能否给出一点建议,多谢!

**Comment by wasden** [comment]
这是点击了才会自动触发还是直接就触发了，这个没遇到过。可以检查一下vim 配置的autocmd呢。
不过建议不使用cmp，维护和扩展都很困难，毕竟它是用来补全的， 可以单独做一个。
我之前也是中英文混输有问题。是cmp的坑，看了很久。

**Comment by yaowjit** [comment]
![Peek 2023-02-13 21-20](https://user-images.githubusercontent.com/36393630/218469281-c4b26991-c5bc-4bcc-a478-81830e7652b1.gif)

就像这样 当前面有英文单词的时候, 如果是按<backspace>删除到这个单词的位置,会自动触发补全,然而这个时候我还没有进行输入呢,也就是必须要有一个空格才能分隔开, 如果是按左右键到这个位置反而不会自动触发,但是这个时候如果想输入中文,按一两个按键触发了输入法补全,但是又把前面的单词匹配进入了输入法补全

扩展性方面倒是不用担心,我用了[rime_lua](https://github.com/zhaozg/rime_lua)这个库,这个库用luajit实现了对rime-api的封装,我在此基础上修改调用的librime, 因为neovim内置了luajit所以调用起来还是很方便的

我现在可以 中英文混输的时候预选中第一项然后空格上屏中文,回车上屏英文,这个跟一般输入法前端差不多

其他比如同步翻页虽然有点难度但也还是可以完成的,就是这个自动匹配挺烦的不知道怎么解决
